# Generated by Django 3.2.11 on 2022-01-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayapp', '0002_auto_20220128_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay_table',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
