# Generated by Django 3.2.11 on 2022-01-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayapp', '0003_razorpay_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpay_table',
            name='name',
        ),
    ]
